# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6514e438db632d1d505b2b9ff144d3ed1132d9db62d3ae3b8d1df310eadcc2004beedffb2584c26de8c2f469d86ff3baddd73b5d0b65cc038f7e391e2b9d0e2f

test:
  secret_key_base: 1c4b3b2a8eadfdfcd981a1ee8baca6090b072a10287963786a38be7d55b16d3e8169ccc47b51fc2293721aedad65ecac8ad2caa5bbffb83cc8a413f23f901c42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
